category/urls.py
from django.conf.urls import url
from category import views
urlpatterns = [
     url(r'^(?P<category>[A-Z]+)/$',views.mobile_phones,name="category"),
    url(r'^brand',views.brands,name="brand"),
    url(r'^state',views.state,name="state"),
    url(r'^accessory',views.accessory,name="accessory"),   
]

online_store/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('store.urls',namespace="store")),
    url(r'^category/',include('category.urls',namespace="category")),
    url(r'^search/',include('search.urls',namespace="search"))
]

if settings.DEBUG:
    urlpatterns +=[
         url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT,}),
    ]

search/urls.py
from django.conf.urls import url
from search import views

urlpatterns = [
    url(r'^',views.product_search_list, name="product_search")
]

store/urls.py
from django.conf.urls import url
from store import views


urlpatterns = [
    url(r'^$',views.Main,name="home"), 
    url(r'^products/(?P<page_id>\d+)/$',views.new_product_list,name="newProducts"),
    url(r'^item_info/(?P<item_id>\d+)/$',views.item_info, name="itemInfo"),
    url(r'^about',views.about, name="about"),
       
]

templates/about.html
{%extends "base.html"%}
{%load static%}

{%block content%}
<h1>About this Page</h1>
{%endblock%}

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">  
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      
      <!--My css-->
    <link rel="stylesheet" href="{%static "css/main_page.css" %}">
    <link rel="stylesheet" href="{%static "css/item_info_css.css" %}">
      <link rel="stylesheet" href="{%static "css/item_page.css" %}">

      <!--inline css to be changed later-->
      <style type="text/css">
          .item_row{
              margin-right: 44px;
              margin-left: 0px;
          }
      </style>
     <!--inline end-->
    <title>Hello, world!</title>
  </head>
  <body>
      <!--bootstrap nav -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="{%url 'store:home'%}">Eddy's Store</a>
        <form class="form-inline my-2 my-lg-0" action="{%url 'search:product_search'%}" method="get">
        <div class="input-group">
      <div class="input-group-prepend">
          
         <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
    <a class="dropdown-item" href="{%url "category:category" "MOB"%}">Mobile Phones</a>
              <a class="dropdown-item" href="{% url "category:category" "COM"%}">Computers</a>
              <a class="dropdown-item" href="{% url "category:category" "MBA"%}">Mobile Accessories</a>
              <a class="dropdown-item" href="{% url "category:category" "CMA"%}">Computer Accessories</a>
                <a class="dropdown-item" href="{% url "category:category" "O"%}">Other</a>
            </div>
          </div>
                    
      </div>
            </div>
          <input class="form-control mr-sm-2" required=required type="text" name="k" id="search" placeholder="what do you want.." aria-label="Search">
            <input type="hidden" name="page" value="1">
            <!--Submit button -->
          <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="search">
            <!--submit ends -->
        </form>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{%url "store:home" %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'store:about'%}">About Store</a>
          </li>
          
        </ul>
         </div>
    </nav>
      <!--bootstrap nav ends-->
      
      <div id ="tag">Home</div>
      
      
     
      {%block content%}
      
        <div class="container">
        <div class="row">
         <div class="col-md-8">
             
             <!-- carosel slider with indicators -->             
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="" width="200px" height="300px" alt="First slide">
    </div>
      {%for img in img_obj%}
      {%if img%}
    <div class="carousel-item">
      <img class="d-block w-100" src="{{img.image.url}}" width="200px" height="300px" alt="Second slide">
    </div>
      {%endif%}
      {%endfor%}
     
 <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
             
       </div>
            </div>
            <!-- end of Carosel slider-->
           
             <!--ads section-->
            <div class="col-md-4 bg-success" id="mainPageAd" >
                <a href=""><div style="float: left; padding:5px; height:100px; width:100px; background-color: red; margin:2px"><img width="90px" height="90px" src="{% static  'img/logos/Blackberry.svg'%}"></div></a>
                
                 <div style="float: left;height:100px; width:100px; background-color: red; margin:2px">
                <img width="90px" height="90px" src="{% static  'img/logos/Apple.svg'%}"></div>
                
            
                 <div style="float: left;height:100px; width:100px; background-color: red; margin:2px">
            <img width="90px" height="90px" src="{% static  'img/logos/Samsung.svg'%}"></div>
            
                 <div style="float: left;height:100px; width:100px; background-color: red; margin:2px">
      <img width="90px" height="90px" src="{% static  'img/logos/Nokia.svg'%}"></div>
    
                 <div style="float: left;height:100px; width:100px; background-color: red; margin:2px"></div>
            
             <!--ads section ends-->
        </div>
      <h1>Latest Products</h1>
      <div class="container">
        <!-- Latest items to be displayed here -->
        <div class="row item_row">
            {%if products.object_list%}
            {% for x in products.object_list%}
          <div class="col-md-3">
            <div class="card" style="width: 19rem;margin-left: 10px">
                {%if x.gp_main_img%}
                <a href="{{x.get_absolute_url}}">
     <img src="{{x.gp_main_img.url}}" width="140" height="170" class="card-img-top" alt="...">
                </a>
                {%else%}
                  <a href="{{x.get_absolute_url}}">
  <img src="{% static "img/default.png" %}" width="140" height="170" class="card-img-top" alt="no image">
                </a>
                {%endif%}
  <div class="card-body">
    <h5 class="card-title" style="font-size:0.8em;">{{x.gp_name}}</h5>
      <p class="card-text"><small>Price:</small><i>D{{x.gp_price}}</i></p>
      <p class="card-text" id="state"><small>State:</small><b>{{x.gp_state}}</b></p>
      <p class="card-text"><small>Views:</small><b>0</b></p>
    <a href="{{x.get_absolute_url}}" style="font-size:0.9em;">More Info&raquo;</a>
      </div>
       </div>
          </div>
            {%endfor%}
            {%else%}
            <h2>No products Sorry..</h2>
            {%endif%}
                    
          </div>
          <!--Latest items end-->
        </div>
   <!-- Pagination-->
          
  <ul class="pagination">
      
           {%if products.has_previous%}
      <li class="page-item">
      <a class="page-link" href="?page={{products.previous_page_number}}" aria-label="Previous">
           <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
       {%endif%}
             
      {%for x in paginate%}
    <li class="page-item"><a class="page-link" href="{%url 'store:newProducts' x%}">{{x}}</a></li>
      {%endfor%}
      
            
     {%if products.has_next%}
    <li class="page-item">
      <a class="page-link" href="?page={{products.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
      {%endif%}
      
  </ul>
          <!-- pagination ends-->
        <hr>
         <!-- container -->
      </div>
        {%endblock%}
          
  
     <!-- Footer -->
<footer class="page-footer font-small unique-color-dark">

  <div style="background-color: #6351ce;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Check us out on social media!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">Company name</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Top brands</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!">Samsung</a>
        </p>
        <p>
          <a href="#!">Iphone</a>
        </p>
        <p>
          <a href="#!">Sony</a>
        </p>
        <p>
          <a href="#!">Techno</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Services</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!">Software Development</a>
        </p>
        <p>
          <a href="#!">Networking</a>
        </p>
        <p>
          <a href="#!">Computer repair</a>
        </p>
      

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> Brusubi, The Gambia</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> ed.sarr7@gmail.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> +220 3126275</p>
        <p>
          <i class="fas fa-print mr-3"></i> +220 2500878</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
      <!--Footer ends-->
      
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
      <script src="{%static "js/main_page.js"%}"></script>
  </body>
</html>

templates/item_info.html
{%extends "base.html"%}
{%load static%}

{%block content%}
   <!-- item information starts here -->
   <div class="container-fluid">
    <div class="content-wrapper">	
		<div class="item-container">	
			<div class="container">	
				<div class="col-md-12">
					<div class="product col-md-3 service-image-left">
                    
						<center>
							<img id="item-display" src="{%static "img/nicePicture.jpg"%}" alt=""></img>
						</center>
					</div>
					
					<div class="container service1-items col-sm-2 col-md-2 pull-left">
						<center>
							<a id="item-1" class="service1-item">
								<img src="{%static "img/nicePicture.jpg"%}" alt=""></img>
							</a>
							<a id="item-2" class="service1-item">
								<img src="{%static "img/nicePicture.jpg"%}" alt=""></img>
							</a>
							<a id="item-3" class="service1-item">
								<img src="{%static "img/nicePicture.jpg"%}" alt=""></img>
							</a>
						</center>
					</div>
				</div>
					
				<div class="col-md-7">
					<div class="product-title">{{items.gp_name}}
                    <p><a id="category" href="{%url 'category:category' items.gp_category%}">{{items.gp_category}}</a></p>
                    </div>
					<div class="product-desc">{{items.gp_description}}</div>
					<div class="product-rating"><i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star-o"></i> </div>
					<hr>
					<div class="product-price">D {{items.gp_price}}
                     <p id="state">{{items.gp_state}}</p>
                    </div>
					<div class="product-stock">{{items.gp_quantity}} In Stock</div>
					<hr>
					<div class="btn-group cart">
				    </div>
					<div class="btn-group wishlist">
						<button type="button" class="btn btn-danger">
							Add to wishlist 
						</button>
					</div>
				</div>
			</div> 
		</div>
		<div class="container-fluid">		
			<div class="col-md-12 product-info">
					<ul id="myTab" class="nav nav-tabs nav_tabs">
                        
						<li class="active"><a href="#service-one" data-toggle="tab">Product Info</a></li>
						<li><a href="#service-two" data-toggle="tab">Reviews</a></li>
                        
					</ul>
                
				<div id="myTabContent" class="tab-content">
						<div class="tab-pane fade in active" id="service-one">
						 
							<section class="container product-info">
				          
                            {%if more_items%}
                              <ul>                 
                             {%for x in more_items%}
                             <li>{{x}}</li>
                                 {%endfor%}                 
                                   </ul>
                                     {%else%}
                                       <p>No extra info..</p>
                                          {%endif%}
                            
							</section>
										  
						</div>
					<div class="tab-pane fade" id="service-two">
						
						<section class="container">
								 Product Review Part
						</section>
						
					</div>
					
				</div>
				<hr>
			</div>
		</div>
	</div>
</div>
  <!-- item information ends-->
        
<div class="row"><div class="col-md-12 bg-success">
      </div></div>

<h1>Related Items</h1>
  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <!-- item block-->
      <div class="col-sm-3">
          <!-- Related items to be displayed here -->
        <div class="container">        
        <div class="row">
             <div class="col-md-3">
            <div class="card" style="width: 17rem;">
  <img src="{% static "img/default.png" %}" width="140" height="170" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="font-size:0.8em;">samsung</h5>
      <p class="card-text"><small>Price:</small><i>23,000</i></p>
      <p class="card-text"><small>State:</small><b>New</b></p>
      <p class="card-text"><small>Views:</small><b>0</b></p>
    <a href="#" style="font-size:0.9em;">More Info&raquo;</a>
      </div>
       </div>
          </div>
                             
          </div>         
          </div>
           <!--Related items end-->
          
        </div>
      <!-- item block ends-->
        <!-- item block-->
      <div class="col-sm-3">
          <!-- Related items to be displayed here -->
        <div class="container">        
        <div class="row">
             <div class="col-md-3">
            <div class="card" style="width: 17rem;">
  <img src="{% static "img/default.png" %}" width="140" height="170" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="font-size:0.8em;">samsung</h5>
      <p class="card-text"><small>Price:</small><i>23,000</i></p>
      <p class="card-text"><small>State:</small><b>New</b></p>
      <p class="card-text"><small>Views:</small><b>0</b></p>
    <a href="#" style="font-size:0.9em;">More Info&raquo;</a>
      </div>
       </div>
          </div>
                             
          </div>         
          </div>
           <!--Related items end-->
          
        </div>
      <!-- item block ends-->
        <!-- item block-->
      <div class="col-md-3">
          <!-- Related items to be displayed here -->
        <div class="container">        
        <div class="row">
             <div class="col-md-3">
            <div class="card" style="width: 17rem;">
  <img src="{% static "img/default.png" %}" width="140" height="170" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="font-size:0.8em;">samsung</h5>
      <p class="card-text"><small>Price:</small><i>23,000</i></p>
      <p class="card-text"><small>State:</small><b>New</b></p>
      <p class="card-text"><small>Views:</small><b>0</b></p>
    <a href="#" style="font-size:0.9em;">More Info&raquo;</a>
      </div>
       </div>
          </div>
                             
          </div>         
          </div>
           <!--Related items end-->
          
        </div>
      <!-- item block ends-->
        <!-- item block-->
      <div class="col-md-3">
          <!-- Related items to be displayed here -->
        <div class="container">        
        <div class="row">
             <div class="col-md-3">
            <div class="card" style="width: 17rem;">
  <img src="{% static "img/default.png" %}" width="140" height="170" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="font-size:0.8em;">samsung</h5>
      <p class="card-text"><small>Price:</small><i>23,000</i></p>
      <p class="card-text"><small>State:</small><b>New</b></p>
      <p class="card-text"><small>Views:</small><b>0</b></p>
    <a href="#" style="font-size:0.9em;">More Info&raquo;</a>
      </div>
       </div>
          </div>
                             
          </div>         
          </div>
           <!--Related items end-->
          
        </div>
      <!-- item block ends-->
      
    </div>
      <!--row of colunms ends-->
      <button class="btn">Show more</button>
      
      <!--ads section-->
            <div class="col-md-3 bg-success" >
                <h1>ads</h1>
            </div>
    <!--ads section ends-->
    <hr>

  </div> <!-- /container -->


{%endblock%}

templates/products.html
{%extends 'base.html'%}
{%load static%}

{%block content%}
<div class="container">
        <!-- Latest items to be displayed here -->
        <div class="row">
            {%if object%}
            {% for x in object%}
          <div class="col-md-3">
            <div class="card" style="width: 17rem;">
  <img src="{% static "img/default.png" %}" width="140" height="170" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="font-size:0.8em;">{{x.gp_name}}</h5>
      <p class="card-text"><small>Price:</small><i>{{x.gp_price}}</i></p>
      <p class="card-text"><small>State:</small><b id="state">{{x.gp_state}}</b></p>
      <p class="card-text"><small>Views:</small><b>0</b></p>
    <a href="#" style="font-size:0.9em;">More Info&raquo;</a>
      </div>
       </div>
          </div>
            {%endfor%}
            {%else%}
            <h2>No products Sorry..</h2>
            {%endif%}
                    
          </div>
          <!--Latest items end-->
        </div>
       <!-- Pagination-->
          
  <ul class="pagination">
      
           {%if products.has_previous%}
      <li class="page-item">
      <a class="page-link" href="?page={{products.previous_page_number}}" aria-label="Previous">
           <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
       {%endif%}
             
      {%for x in paginate%}
    <li class="page-item"><a class="page-link" href="{%url 'store:newProducts' x%}">{{x}}</a></li>
      {%endfor%}
            
     {%if products.has_next%}
    <li class="page-item">
      <a class="page-link" href="?page={{products.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
      {%endif%}
      
  </ul>
          <!-- pagination ends-->
{%endblock%}